pipeline {
    agent any

    stages {
        stage('Dev') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/AdminTurnedDevOps/go-webbapp-sample.git'
            }
        }

        stage('UAT') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/AdminTurnedDevOps/go-webbapp-sample.git'
            }
        }
    }
}