pipeline {
    agent any

    tools {
        go 'go-1.17'
    }

    environment {
        GO111MODULE='on'
    }

    stages{
        stage('Test') {
            steps {
                git 'https://github.com/AdminTurnedDevOps/go-webbapp-sample.git'
                sh 'go test ./...'
            }
        }
    }
}